- name: demo on loops
  hosts: localhost
  become: yes
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello {{item}}"

    loop:
    - Linux
    - Shell
    - ansible

  - name: install packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - postfix
    - mysql-server

  - name: install packages
    ansible.builtin.apt:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: 'nginx', state: 'absent' }
    - { name: 'postfix', state: 'absent' }
    - { name: 'mysql-server', state: 'absent' }          
