- name: variables
  hosts: localhost
  vars:
    course: "Ansible"
    Trainer: "Sivakumar"
    Duration: "120hrs"
  tasks:
  - name: print info1
    vars:
      course: "Terraform"
    ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} from trainer {{Trainer}}, duration is {{Duration}}."
  
  - name: print info2
    ansible.builtin.debug:
      msg: "Hi, we are learning {{course}} from trainer {{Trainer}}, duration is {{Duration}}."    